<script>
  import { link } from 'svelte-spa-router'
  import active from 'svelte-spa-router/active'
</script>

<header>
    <ol>
        <li>
            <a
                    href="/1"
                    use:link
                    use:active>
                선언적 랜더링
            </a>

        </li>
        <li>
            <a
                    href="/2"
                    use:link
                    use:active>
                조건문
            </a>
        </li>
        <li>
            <a
                    href="/3"
                    use:link
                    use:active>
                반복문
            </a>
        </li>
        <li>
            <a
                    href="/4"
                    use:link
                    use:active>
                이벤트핸들링
            </a>
        </li>
        <li>
            <a
                    href="/5"
                    use:link
                    use:active>
                바인딩
            </a>
        </li>
        <li>
            <a
                    href="/6"
                    use:link
                    use:active>
                컴포넌트
            </a>
        </li>
        <li>
            <a
                    href="/7"
                    use:link
                    use:active>
                스토어
            </a>
        </li>
        <li>
            <a
                    href="/8"
                    use:link
                    use:active>
                투두리스트 예제
            </a>
        </li>
        <li>
            <a
                    href="/9"
                    use:link
                    use:active>
                라이프사이클
            </a>
        </li>
        <li>
            <a
                    href="/10"
                    use:link
                    use:active>
                tick
            </a>
        </li>
        <li>
            <a
                    href="/11"
                    use:link
                    use:active>
                라이프사이클 모듈화
            </a>
        </li>
        <li>
            <a
                    href="/12"
                    use:link
                    use:active>
                기본 보간
            </a>
        </li>
        <li>
            <a
                    href="/13"
                    use:link
                    use:active>
                원시 HTML
            </a>
        </li>
        <li>
            <a
                    href="/14"
                    use:link
                    use:active>
                디버그
            </a>
        </li>
        <li>
            <a
                    href="/15"
                    use:link
                    use:active>
                반응성 할당
            </a>
        </li>
        <li>
            <a
                    href="/16"
                    use:link
                    use:active>
                반응성 구문
            </a>
        </li>
        <li>
            <a
                    href="/17"
                    use:link
                    use:active>
                스타일 속성 바인딩
            </a>
        </li>
        <li>
            <a
                    href="/18"
                    use:link
                    use:active>
                스타일 사용패턴
            </a>
        </li>
        <li>
            <a
                    href="/19"
                    use:link
                    use:active>
                스타일 유효범위 전역화
            </a>
        </li>
        <li>
            <a
                    href="/20"
                    use:link
                    use:active>
                일반 요소 바인딩
            </a>
        </li>
        <li>
            <a
                    href="/21"
                    use:link
                    use:active>
                입력 요소 바인딩
            </a>
        </li>
        <li>
            <a
                    href="/22"
                    use:link
                    use:active>
                편집가능 요소 바인딩
            </a>
        </li>
        <li>
            <a
                    href="/23"
                    use:link
                    use:active>
                조건블록
            </a>
        </li>
        <li>
            <a
                    href="/24"
                    use:link
                    use:active>
                반복블록
            </a>
        </li>
        <li>
            <a
                    href="/25"
                    use:link
                    use:active>
                반복블록 사용패턴
            </a>
        </li>
        <li>
            <a
                    href="/26"
                    use:link
                    use:active>
                키블록
            </a>
        </li>
        <li>
            <a
                    href="/27"
                    use:link
                    use:active>
                비동기블록
            </a>
        </li>
        <li>
            <a
                    href="/28"
                    use:link
                    use:active>
                사용자입력 핸들링
            </a>
        </li>
        <li>
            <a
                    href="/29"
                    use:link
                    use:active>
                다중이벤트핸들링
            </a>
        </li>
        <li>
            <a
                    href="/30"
                    use:link
                    use:active>
                이벤트수식어
            </a>
        </li>
        <li>
            <a
                    href="/31"
                    use:link
                    use:active>
                컴포넌트
            </a>
        </li>
        <li>
            <a
                    href="/32"
                    use:link
                    use:active>
                Props
            </a>
        </li>
        <li>
            <a
                    href="/33"
                    use:link
                    use:active>
                양방향바인딩
            </a>
        </li>
        <li>
            <a
                    href="/34"
                    use:link
                    use:active>
                Event Dispatcher
            </a>
        </li>
        <li>
            <a
                    href="/35"
                    use:link
                    use:active>
                Event Forwarding
            </a>
        </li>
        <li>
            <a
                    href="/36"
                    use:link
                    use:active>
                Context API
            </a>
        </li>
        <li>
            <a
                    href="/37"
                    use:link
                    use:active>
                Module Context1
            </a>
        </li>
        <li>
            <a
                    href="/38"
                    use:link
                    use:active>
                Module Context2
            </a>
        </li>
        <li>
            <a
                    href="/39"
                    use:link
                    use:active>
                $$props, $$restProps
            </a>
        </li>
        <li>
            <a
                    href="/40"
                    use:link
                    use:active>
                Slot
            </a>
        </li>
        <li>
            <a
                    href="/41"
                    use:link
                    use:active>
                단일 슬롯과 Fallback Content
            </a>
        </li>
        <li>
            <a
                    href="/42"
                    use:link
                    use:active>
                이름을 가지는 슬롯
            </a>
        </li>
        <li>
            <a
                    href="/43"
                    use:link
                    use:active>
                범위를 가지는 슬롯1
            </a>
        </li>
        <li>
            <a
                    href="/44"
                    use:link
                    use:active>
                범위를 가지는 슬롯2
            </a>
        </li>
        <li>
            <a
                    href="/45"
                    use:link
                    use:active>
                슬롯포워딩
            </a>
        </li>
        <li>
            <a
                    href="/46"
                    use:link
                    use:active>
                $$slots
            </a>
        </li>
        <li>
            <a
                    href="/47"
                    use:link
                    use:active>
                스토어
            </a>
        </li>
        <li>
            <a
                    href="/48"
                    use:link
                    use:active>
                쓰기 가능 스토어1
            </a>
        </li>
        <li>
            <a
                    href="/49"
                    use:link
                    use:active>
                쓰기 가능 스토어2
            </a>
        </li>
        <li>
            <a
                    href="/50"
                    use:link
                    use:active>
                읽기 가능 스토어
            </a>
        </li>
        <li>
            <a
                    href="/51"
                    use:link
                    use:active>
                계산된 스토어
            </a>
        </li>
        <li>
            <a
                    href="/52"
                    use:link
                    use:active>
                스토어 값얻기
            </a>
        </li>
        <li>
            <a
                    href="/53"
                    use:link
                    use:active>
                액션1
            </a>
        </li>
        <li>
            <a
                    href="/54"
                    use:link
                    use:active>
                액션1
            </a>
        </li>
        <li>
            <a
                    href="/55"
                    use:link
                    use:active>
                특별한 요소 self
            </a>
        </li>
        <li>
            <a
                    href="/56"
                    use:link
                    use:active>
                특별한 요소 component
            </a>
        </li>
        <li>
            <a
                    href="/57"
                    use:link
                    use:active>
                특별한 요소 window
            </a>
        </li>
        <li>
            <a
                    href="/58"
                    use:link
                    use:active>
                특별한 요소 Head Body
            </a>
        </li>
        <li>
            <a
                    href="/59"
                    use:link
                    use:active>
                특별한 요소 options
            </a>
        </li>
        <li>
            <a
                    href="/60"
                    use:link
                    use:active>
                특별한 요소 options accessor
            </a>
        </li>
        <li>
            <a
                    href="/61"
                    use:link
                    use:active>
                애니메이션 tweened
            </a>
        </li>
        <li>
            <a
                    href="/62"
                    use:link
                    use:active>
                svelte-spa-router
            </a>
        </li>
        <li>
            <a
                    href="/63"
                    use:link
                    use:active>
                전/후_처리기(svelte-preprocess)
            </a>
        </li>
        <li>
            <a
                    href="/64"
                    use:link
                    use:active>
                Unit 테스트 Jest
            </a>
        </li>
        <li>
            <a
                    href="/65"
                    use:link
                    use:active>
                Web Test runner
            </a>
        </li>
        <li>
            <a
                    href="/66"
                    use:link
                    use:active>
                Svelte Devtools
            </a>
        </li>

    </ol>

</header>

<style>
    :global(header a.active) {
        font-weight: bold;
        text-decoration: underline;
    }
</style>
